### PR TITLE
Support for CT lights

### PR DESCRIPTION
**Pull request by off-my-lawn**
Create the relevant properties required for #14 .

This includes the conversions between Kelvin and the units Tasmota uses for color temperature.

The webthings UI updates between a white and orange globe. However, for reasons that I am so far unable to determine the UI always assigns the value to 50 instead of any value I enter. As a result I can't assign a color temperature. I'd be very happy if there's something I missed, either way I think reading the color temperature is still helpful.

### CODE REVIEW

**Comment by tim-hellhake** [comment]
Thank you very much for your help!

> the UI always assigns the value to 50 instead of any value I enter.

I'll try to reproduce it locally.
One thing I would definitely recommend is setting the `minimum`  and the ` maximum`  value of the CT property.

**Comment by off-my-lawn** [comment]
I did try changing those values manually in the browser inspector (both were undefined). Didn't seem to make any difference, probably be two days before I get another chance to look into it.

**Comment by off-my-lawn** [comment]
That made the difference. With the changes now here it's working nicely.

**Comment by tim-hellhake** [comment]
Perfect!
I have a few little remarks like _const instead of var_, but I think I'll just merge it and change it afterward.

**Comment by tim-hellhake** [comment]
@off-my-lawn
I created a few tests for the ct conversion: [ct-conversion.spec.ts](https://github.com/tim-hellhake/tasmota-adapter/blob/master/src/ct-conversion.spec.ts).
Can you please check if it makes sense?
I'm not familiar with the ct range of tasmota.

**Comment by tim-hellhake** [comment]
I also added tests for `undefined` and `null`.
As you can see in the test cases, the conversion behaves differently.
I'm not sure which makes more sense.
I would tend not to update the UI at all if the Tasmota returns invalid values.

**Comment by off-my-lawn** [comment]
I'll have a look at the tests tonight. Yeah it's a weird scale Tasmota is using, not sure if it was meant to mean anything.

Unless I'm mistaken the var instead of const was because I used its value to check if it needed an alternate value.

**Pull request merged**
