### PR TITLE
Support RGBW lights

### PR DESCRIPTION
**Pull request by off-my-lawn**
The minimum for reasonable behavior for #11 is to check for a color length of 8, and to trim the color back down to 6 so the WebThings UI shows the color selected.

Adding support for a brightness property is just to be nice.

Changing the OnOffProperty to query the tasmota Power property allows the color selected in WebThings to be persisted.

I'm happy to split those out into separate requests or adjust coding style if there's any changes you would like.

### CODE REVIEW

**Comment by tim-hellhake** [comment]
> Changing the OnOffProperty to query the tasmota Power property allows the color selected in WebThings to be persisted.

Good idea.

> I'm happy to split those out into separate requests or adjust coding style if there's any changes you would like.

Actually the code looks really good.
I'll merge it like it is.
One thing though.
I will deactivate the brightness property before the release.
The IoT team decided against separate brightness properties because the brightness is part of the color.
You can change it in the color picker dialog.

**Comment by tim-hellhake** [comment]
I found a little bug 😅.
`'01234578'.substring(6)` results in `78`.
I think what you meant was `substring(0, 6)`.

**Comment by tim-hellhake** [comment]
Are you sure the `Power` commands works for the lights?
I can see no difference in the color values when executing `Power 0`.

**Comment by off-my-lawn** [comment]
I noticed the substring error last night.

Setting Power works on my lights.

**Comment by tim-hellhake** [comment]
I fixed the substring error and added a few minor changes: https://github.com/mozilla-iot/addon-list/pull/699

**Pull request merged**
